# Generated by Codex on 2026-02-28

from __future__ import annotations

# Django
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("eve_sde", "0012_alter_constellation_region"),
        ("indy_hub", "0086_materialexchangesellorder_anomaly_rejected_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="SdeMarketGroup",
            fields=[
                ("id", models.BigIntegerField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        db_column="parent_market_group_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="indy_hub.sdemarketgroup",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="SdeIndustryActivityProduct",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("activity_id", models.IntegerField(db_index=True)),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "eve_type",
                    models.ForeignKey(
                        db_column="eve_type_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="industry_products",
                        to="eve_sde.itemtype",
                    ),
                ),
                (
                    "product_eve_type",
                    models.ForeignKey(
                        db_column="product_eve_type_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eve_sde.itemtype",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="SdeIndustryActivityMaterial",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("activity_id", models.IntegerField(db_index=True)),
                ("quantity", models.PositiveIntegerField(default=0)),
                (
                    "eve_type",
                    models.ForeignKey(
                        db_column="eve_type_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="industry_materials",
                        to="eve_sde.itemtype",
                    ),
                ),
                (
                    "material_eve_type",
                    models.ForeignKey(
                        db_column="material_eve_type_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="eve_sde.itemtype",
                    ),
                ),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.AddIndex(
            model_name="sdemarketgroup",
            index=models.Index(fields=["parent"], name="indy_hub_sd_parent__ef0318_idx"),
        ),
        migrations.AddIndex(
            model_name="sdeindustryactivityproduct",
            index=models.Index(
                fields=["eve_type", "activity_id"],
                name="indy_hub_sd_eve_typ_2d4c18_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sdeindustryactivityproduct",
            index=models.Index(
                fields=["product_eve_type", "activity_id"],
                name="indy_hub_sd_produc_23b2bb_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="sdeindustryactivityproduct",
            constraint=models.UniqueConstraint(
                fields=("eve_type", "product_eve_type", "activity_id"),
                name="indy_hub_sdeactivityproduct_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="sdeindustryactivitymaterial",
            index=models.Index(
                fields=["eve_type", "activity_id"],
                name="indy_hub_sd_eve_typ_7a2e7e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sdeindustryactivitymaterial",
            index=models.Index(
                fields=["material_eve_type", "activity_id"],
                name="indy_hub_sd_materi_4cf42a_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="sdeindustryactivitymaterial",
            constraint=models.UniqueConstraint(
                fields=("eve_type", "material_eve_type", "activity_id"),
                name="indy_hub_sdeactivitymaterial_unique",
            ),
        ),
    ]
