# Generated by Django 4.2.21 on 2026-03-11 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indy_hub', '0097_cachedcorporationasset_set_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='esicontractitem',
            name='raw_quantity',
            field=models.IntegerField(blank=True, help_text='Raw quantity from ESI; -1 or -2 indicates item is inside a container', null=True),
        ),
        migrations.AlterField(
            model_name='materialexchangeitempriceoverride',
            name='buy_markup_base_override',
            field=models.CharField(blank=True, choices=[('buy', 'Jita Buy'), ('sell', 'Jita Sell')], help_text='Override base price for buy side markup (Jita Buy or Jita Sell).', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='materialexchangeitempriceoverride',
            name='buy_markup_percent_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override buy markup % applied when members buy from hub (same format as global buy markup).', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='materialexchangeitempriceoverride',
            name='sell_markup_base_override',
            field=models.CharField(blank=True, choices=[('buy', 'Jita Buy'), ('sell', 'Jita Sell')], help_text='Override base price for sell side markup (Jita Buy or Jita Sell).', max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='materialexchangeitempriceoverride',
            name='sell_markup_percent_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override sell markup % applied when members sell to hub (same format as global sell markup).', max_digits=6, null=True),
        ),
    ]
