# Generated by Django 4.2.20 on 2026-03-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indy_hub", "0099_material_exchange_transaction_jita_snapshots"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialexchangeconfig",
            name="container_price_overrides",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text=(
                    "Pricing overrides for items inside containers/cans. Supports fixed price and/or markup "
                    "overrides for sell and buy sides."
                ),
            ),
        ),
    ]
