# Generated by Django 4.2.20 on 2026-03-13 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("indy_hub", "0100_materialexchangeconfig_container_price_overrides"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CapitalShipOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ship_type_id",
                    models.IntegerField(help_text="Requested hull type ID"),
                ),
                ("ship_type_name", models.CharField(blank=True, max_length=255)),
                (
                    "ship_class",
                    models.CharField(
                        choices=[
                            ("dread", "Dreadnought"),
                            ("carrier", "Carrier"),
                            ("fax", "Force Auxiliary"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            (
                                "no_cap",
                                "I currently have no cap of this type and need one to be minimally combat effective.",
                            ),
                            (
                                "alt_needs_cap",
                                "I currently have at least one cap of this type, but another pilot needs one to be minimally combat effective.",
                            ),
                            (
                                "backup",
                                "I currently have at least one cap for all pilots. This order is for backup/reship/aux.",
                            ),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("waiting", "Waiting"),
                            ("in_production", "In Production"),
                            ("contract_created", "Contract Created"),
                            ("completed", "Contract Completed"),
                            ("anomaly", "Anomaly"),
                        ],
                        default="waiting",
                        max_length=32,
                    ),
                ),
                (
                    "order_reference",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Unique capital order reference (INDY-CAP-###).",
                        max_length=32,
                        unique=True,
                    ),
                ),
                (
                    "esi_contract_id",
                    models.BigIntegerField(
                        blank=True,
                        db_index=True,
                        help_text="Matched ESI contract ID.",
                        null=True,
                    ),
                ),
                ("in_production_at", models.DateTimeField(blank=True, null=True)),
                ("contract_created_at", models.DateTimeField(blank=True, null=True)),
                ("contract_completed_at", models.DateTimeField(blank=True, null=True)),
                ("anomaly_reason", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capital_ship_orders",
                        to="indy_hub.materialexchangeconfig",
                    ),
                ),
                (
                    "in_production_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="capital_orders_set_in_production",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capital_ship_orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Capital Ship Order",
                "verbose_name_plural": "Capital Ship Orders",
                "ordering": ["-created_at"],
                "default_permissions": (),
                "indexes": [
                    models.Index(fields=["status", "-created_at"]),
                    models.Index(fields=["requester", "-created_at"]),
                    models.Index(fields=["esi_contract_id"]),
                ],
            },
        ),
        migrations.AddField(
            model_name="materialexchangebuyorder",
            name="source_location_id",
            field=models.BigIntegerField(
                blank=True,
                help_text="Resolved buy location ID selected for this order.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="materialexchangebuyorder",
            name="source_location_name",
            field=models.CharField(
                blank=True,
                help_text="Resolved buy location name selected for this order.",
                max_length=255,
            ),
        ),
    ]
