# Generated by Django 4.2.20 on 2026-03-13 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indy_hub", "0101_capitalshiporder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="capitalshiporder",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting"),
                    ("in_production", "In Production"),
                    ("contract_created", "Contract Created"),
                    ("completed", "Contract Completed"),
                    ("anomaly", "Anomaly"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                default="waiting",
                max_length=32,
            ),
        ),
    ]
