# Generated by Django 4.2.20 on 2026-03-25 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("indy_hub", "0105_reprocessingserviceprofile_admin_force_unavailable"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="materialexchangeconfig",
            name="capital_auto_cancel_delay_unit",
            field=models.CharField(
                choices=[("hours", "Hours"), ("days", "Days")],
                default="hours",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="materialexchangeconfig",
            name="capital_auto_cancel_delay_value",
            field=models.PositiveIntegerField(
                default=0,
                help_text=(
                    "Grace period before auto-cancel once requester is in the wrong state. "
                    "0 means immediate."
                ),
            ),
        ),
        migrations.AddField(
            model_name="materialexchangeconfig",
            name="capital_auto_cancel_eligible_statuses",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text=(
                    "Capital order statuses eligible for auto-cancel when requester "
                    "leaves preapproved state."
                ),
            ),
        ),
        migrations.AddField(
            model_name="materialexchangeconfig",
            name="capital_auto_cancel_on_state_change",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Automatically cancel eligible capital orders when requester leaves "
                    "the configured preapproved state."
                ),
            ),
        ),
        migrations.AddField(
            model_name="materialexchangeconfig",
            name="capital_auto_cancel_preapproved_state_names",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text=(
                    "State names treated as preapproved for capital-order auto-cancel checks."
                ),
            ),
        ),
        migrations.AddField(
            model_name="materialexchangeconfig",
            name="capital_custom_ship_options",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text=(
                    "Custom capital menu entries. Each row should define type_id, "
                    "type_name, ship_class, optional ship_class_label, and optional enabled."
                ),
            ),
        ),
        migrations.AddField(
            model_name="materialexchangeconfig",
            name="capital_disabled_ship_type_ids",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text=(
                    "Ship type IDs hidden from the capital order menu for this configuration."
                ),
            ),
        ),
        migrations.AddField(
            model_name="materialexchangeconfig",
            name="capital_default_eta_max_days_carrier",
            field=models.PositiveSmallIntegerField(default=28),
        ),
        migrations.AddField(
            model_name="materialexchangeconfig",
            name="capital_default_eta_max_days_dread",
            field=models.PositiveSmallIntegerField(default=28),
        ),
        migrations.AddField(
            model_name="materialexchangeconfig",
            name="capital_default_eta_max_days_fax",
            field=models.PositiveSmallIntegerField(default=28),
        ),
        migrations.AddField(
            model_name="materialexchangeconfig",
            name="capital_default_eta_min_days_carrier",
            field=models.PositiveSmallIntegerField(default=14),
        ),
        migrations.AddField(
            model_name="materialexchangeconfig",
            name="capital_default_eta_min_days_dread",
            field=models.PositiveSmallIntegerField(default=14),
        ),
        migrations.AddField(
            model_name="materialexchangeconfig",
            name="capital_default_eta_min_days_fax",
            field=models.PositiveSmallIntegerField(default=14),
        ),
        migrations.AddField(
            model_name="materialexchangeconfig",
            name="capital_default_lead_time_days",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Default lead-time days added to generated ETA guidance.",
            ),
        ),
        migrations.AddField(
            model_name="materialexchangeconfig",
            name="capital_default_price_carrier",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Default internal guideline price for carrier orders.",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="materialexchangeconfig",
            name="capital_default_price_dread",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Default internal guideline price for dread orders.",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="materialexchangeconfig",
            name="capital_default_price_fax",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Default internal guideline price for FAX orders.",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="capitalshiporder",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting"),
                    ("gathering_materials", "Gathering Materials"),
                    ("in_production", "In Production"),
                    ("contract_created", "Contract Created"),
                    ("completed", "Contract Completed"),
                    ("anomaly", "Anomaly"),
                    ("rejected", "Rejected"),
                    ("cancelled", "Cancelled"),
                ],
                default="waiting",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="capitalshiporder",
            name="agreement_locked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="capitalshiporder",
            name="agreed_price_isk",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="capitalshiporder",
            name="definitive_eta_max_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="capitalshiporder",
            name="definitive_eta_min_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="capitalshiporder",
            name="definitive_eta_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="capitalshiporder",
            name="gathering_materials_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="capitalshiporder",
            name="guideline_eta_max_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="capitalshiporder",
            name="guideline_eta_min_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="capitalshiporder",
            name="guideline_generated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="capitalshiporder",
            name="guideline_price_isk",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="capitalshiporder",
            name="guideline_price_source",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="capitalshiporder",
            name="lead_time_days",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="capitalshiporder",
            name="likely_eta_max_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="capitalshiporder",
            name="likely_eta_min_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="capitalshiporder",
            name="offer_eta_max_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="capitalshiporder",
            name="offer_eta_min_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="capitalshiporder",
            name="offer_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="capitalshiporder",
            name="offer_price_isk",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=20, null=True
            ),
        ),
        migrations.AddField(
            model_name="capitalshiporder",
            name="offer_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="capitalshiporder",
            name="requester_preapproved_mismatch_since",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="capitalshiporder",
            name="user_offer_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="capitalshiporder",
            name="agreement_locked_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="capital_orders_locked_agreements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="capitalshiporder",
            name="definitive_eta_updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="capital_orders_definitive_eta_updates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="capitalshiporder",
            name="gathering_materials_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="capital_orders_set_gathering_materials",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="capitalshiporder",
            name="offer_updated_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="capital_orders_offer_updates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="capitalshiporder",
            name="user_offer_confirmed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="capital_orders_user_offer_confirmations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="CapitalShipOrderChat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_open", models.BooleanField(default=True)),
                ("closed_reason", models.CharField(blank=True, max_length=64)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("last_message_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_message_role",
                    models.CharField(blank=True, max_length=16, null=True),
                ),
                ("requester_last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("admin_last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat",
                        to="indy_hub.capitalshiporder",
                    ),
                ),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="capital_order_chats_as_requester",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Capital Order Chat",
                "verbose_name_plural": "Capital Order Chats",
                "default_permissions": (),
                "indexes": [
                    models.Index(fields=["order_id"], name="cap_chat_order_idx"),
                    models.Index(fields=["requester_id"], name="cap_chat_req_idx"),
                    models.Index(
                        fields=["is_open", "updated_at"], name="cap_chat_state_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CapitalShipOrderEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("offer_updated", "Offer updated"),
                            ("offer_confirmed_by_user", "Offer confirmed by user"),
                            ("offer_rejected_by_user", "Offer rejected by user"),
                            ("status_changed", "Status changed"),
                            (
                                "auto_cancelled_state_mismatch",
                                "Auto-cancelled due to requester state mismatch",
                            ),
                        ],
                        max_length=64,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="capital_order_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="indy_hub.capitalshiporder",
                    ),
                ),
            ],
            options={
                "verbose_name": "Capital Order Event",
                "verbose_name_plural": "Capital Order Events",
                "ordering": ["-created_at", "-id"],
                "default_permissions": (),
                "indexes": [
                    models.Index(
                        fields=["order_id", "created_at"], name="cap_evt_order_idx"
                    ),
                    models.Index(
                        fields=["event_type", "created_at"], name="cap_evt_type_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CapitalShipOrderMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sender_role",
                    models.CharField(
                        choices=[
                            ("requester", "Requester"),
                            ("admin", "Material Exchange Admin"),
                            ("system", "System"),
                        ],
                        max_length=16,
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "chat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="indy_hub.capitalshiporderchat",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="capital_order_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Capital Order Message",
                "verbose_name_plural": "Capital Order Messages",
                "ordering": ["created_at", "id"],
                "default_permissions": (),
                "indexes": [
                    models.Index(
                        fields=["chat_id", "created_at"], name="cap_msg_chat_idx"
                    ),
                ],
            },
        ),
    ]
