# Generated by Django 4.2.20 on 2026-03-25 00:10

from django.db import migrations, models


def _column_exists(schema_editor, table_name, column_name):
    with schema_editor.connection.cursor() as cursor:
        columns = schema_editor.connection.introspection.get_table_description(
            cursor, table_name
        )
    for column in columns:
        name = getattr(column, "name", None)
        if name is None and column:
            name = column[0]
        if name == column_name:
            return True
    return False


def add_missing_capital_config_fields(apps, schema_editor):
    MaterialExchangeConfig = apps.get_model("indy_hub", "MaterialExchangeConfig")
    table_name = MaterialExchangeConfig._meta.db_table

    fields_to_add = [
        (
            "capital_disabled_ship_groups",
            models.JSONField(
                blank=True,
                default=list,
                help_text=(
                    "Ship-group keys hidden from the capital order menu (for example "
                    "dread, carrier, fax)."
                ),
            ),
        ),
        (
            "capital_ship_estimated_price_overrides",
            models.JSONField(
                blank=True,
                default=list,
                help_text=(
                    "Per-ship estimated price overrides. Each row should define "
                    "type_id and price_isk."
                ),
            ),
        ),
    ]

    for field_name, field in fields_to_add:
        if _column_exists(schema_editor, table_name, field_name):
            continue
        field.set_attributes_from_name(field_name)
        schema_editor.add_field(MaterialExchangeConfig, field)


class Migration(migrations.Migration):

    dependencies = [
        ("indy_hub", "0107_add_capital_order_manager_permission"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[
                migrations.RunPython(
                    add_missing_capital_config_fields, migrations.RunPython.noop
                )
            ],
            state_operations=[
                migrations.AddField(
                    model_name="materialexchangeconfig",
                    name="capital_disabled_ship_groups",
                    field=models.JSONField(
                        blank=True,
                        default=list,
                        help_text=(
                            "Ship-group keys hidden from the capital order menu (for "
                            "example dread, carrier, fax)."
                        ),
                    ),
                ),
                migrations.AddField(
                    model_name="materialexchangeconfig",
                    name="capital_ship_estimated_price_overrides",
                    field=models.JSONField(
                        blank=True,
                        default=list,
                        help_text=(
                            "Per-ship estimated price overrides. Each row should define "
                            "type_id and price_isk."
                        ),
                    ),
                ),
            ],
        ),
    ]
