# Generated by Django 4.2 on 2026-04-02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indy_hub", "0109_buyback_label_updates"),
    ]

    operations = [
        migrations.CreateModel(
            name="PublicJitaContract",
            fields=[
                ("contract_id", models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ("region_id", models.IntegerField(db_index=True, default=10000002)),
                ("contract_type", models.CharField(blank=True, db_index=True, max_length=50)),
                ("status", models.CharField(blank=True, db_index=True, max_length=50)),
                ("title", models.TextField(blank=True)),
                ("issuer_id", models.BigIntegerField(db_index=True, default=0)),
                ("issuer_corporation_id", models.BigIntegerField(default=0)),
                ("for_corporation", models.BooleanField(default=False)),
                ("start_location_id", models.BigIntegerField(blank=True, db_index=True, null=True)),
                ("end_location_id", models.BigIntegerField(blank=True, db_index=True, null=True)),
                ("is_jita", models.BooleanField(db_index=True, default=False)),
                ("price", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ("reward", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ("collateral", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ("buyout", models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ("date_issued", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("date_expired", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("last_seen_at", models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ("last_synced", models.DateTimeField(auto_now=True, db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Public Jita Contract",
                "verbose_name_plural": "Public Jita Contracts",
                "default_permissions": (),
                "ordering": ["-date_issued", "-contract_id"],
            },
        ),
        migrations.CreateModel(
            name="PublicJitaContractItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("record_id", models.BigIntegerField()),
                ("type_id", models.IntegerField(db_index=True)),
                ("quantity", models.BigIntegerField(default=0)),
                ("runs", models.IntegerField(default=0)),
                ("is_included", models.BooleanField(db_index=True, default=False)),
                ("is_blueprint_copy", models.BooleanField(db_index=True, default=False)),
                ("is_singleton", models.BooleanField(default=False)),
                ("material_efficiency", models.IntegerField(default=0)),
                ("time_efficiency", models.IntegerField(default=0)),
                ("last_synced", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="indy_hub.publicjitacontract",
                    ),
                ),
            ],
            options={
                "verbose_name": "Public Jita Contract Item",
                "verbose_name_plural": "Public Jita Contract Items",
                "default_permissions": (),
                "unique_together": {("contract", "record_id")},
            },
        ),
        migrations.AddIndex(
            model_name="publicjitacontract",
            index=models.Index(fields=["is_active", "date_expired"], name="indy_hub_pu_is_acti_905bbf_idx"),
        ),
        migrations.AddIndex(
            model_name="publicjitacontract",
            index=models.Index(fields=["region_id", "is_jita", "is_active"], name="indy_hub_pu_region__a03667_idx"),
        ),
        migrations.AddIndex(
            model_name="publicjitacontract",
            index=models.Index(fields=["contract_type", "status", "is_jita"], name="indy_hub_pu_contrac_d4fc28_idx"),
        ),
        migrations.AddIndex(
            model_name="publicjitacontract",
            index=models.Index(fields=["last_seen_at"], name="indy_hub_pu_last_se_680c73_idx"),
        ),
        migrations.AddIndex(
            model_name="publicjitacontract",
            index=models.Index(fields=["-date_issued"], name="indy_hub_pu_date_is_a9841c_idx"),
        ),
        migrations.AddIndex(
            model_name="publicjitacontractitem",
            index=models.Index(fields=["contract", "type_id"], name="indy_hub_pu_contrac_07c967_idx"),
        ),
        migrations.AddIndex(
            model_name="publicjitacontractitem",
            index=models.Index(fields=["type_id", "is_included", "is_blueprint_copy"], name="indy_hub_pu_type_id_0b2136_idx"),
        ),
    ]
