# Generated by Django 4.2 on 2026-04-17

from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indy_hub", "0110_public_jita_contract_cache"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterialExchangeDailySnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("corporation_id", models.BigIntegerField(db_index=True)),
                (
                    "wallet_division",
                    models.IntegerField(
                        validators=[MinValueValidator(1), MaxValueValidator(7)]
                    ),
                ),
                ("snapshot_date", models.DateField(db_index=True)),
                (
                    "inventory_market_value",
                    models.DecimalField(decimal_places=2, default=0, max_digits=20),
                ),
                ("inventory_item_count", models.BigIntegerField(default=0)),
                ("inventory_type_count", models.IntegerField(default=0)),
                ("inventory_priced_type_count", models.IntegerField(default=0)),
                ("inventory_location_count", models.IntegerField(default=0)),
                ("inventory_hangar_count", models.IntegerField(default=0)),
                (
                    "wallet_balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("wallet_balance_available", models.BooleanField(default=False)),
                (
                    "total_asset_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                ("assets_scope_missing", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Buyback Daily Snapshot",
                "verbose_name_plural": "Buyback Daily Snapshots",
                "default_permissions": (),
                "ordering": ["snapshot_date", "corporation_id", "wallet_division"],
            },
        ),
        migrations.AddConstraint(
            model_name="materialexchangedailysnapshot",
            constraint=models.UniqueConstraint(
                fields=("corporation_id", "wallet_division", "snapshot_date"),
                name="me_daily_snapshot_unique_scope",
            ),
        ),
        migrations.AddIndex(
            model_name="materialexchangedailysnapshot",
            index=models.Index(
                fields=["corporation_id", "wallet_division", "snapshot_date"],
                name="me_daily_snapshot_scope_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="materialexchangedailysnapshot",
            index=models.Index(
                fields=["snapshot_date"],
                name="me_daily_snapshot_date_idx",
            ),
        ),
    ]
