# Generated by Django 4.2 on 2026-04-22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indy_hub", "0111_materialexchangedailysnapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialexchangeconfig",
            name="capital_ship_auto_estimated_prices",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text=(
                    "System-managed per-ship estimated prices from public contract "
                    "data. Each row should define type_id, price_isk, and optional "
                    "metadata."
                ),
            ),
        ),
    ]
