# Generated by ChatGPT on 2026-05-11

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indy_hub", "0114_materialexchange_rejection_restore"),
    ]

    operations = [
        migrations.CreateModel(
            name="WeeklyMiningPollConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("system_name", models.CharField(max_length=80)),
                ("poll_name", models.CharField(max_length=180)),
                (
                    "channel_id",
                    models.BigIntegerField(
                        help_text="Discord channel ID used for posting."
                    ),
                ),
                (
                    "ping_role_id",
                    models.BigIntegerField(
                        blank=True,
                        help_text="Optional Discord role ID to ping when the poll is posted.",
                        null=True,
                    ),
                ),
                ("options_json", models.JSONField(blank=True, default=list)),
                ("current_winner_option", models.CharField(blank=True, max_length=55)),
                (
                    "crontab_schedule_id",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="ID of the django-celery-beat crontab schedule to reuse.",
                        null=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "last_scheduled_post_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Last time this config dispatched a weekly poll run.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Weekly Mining Poll Config",
                "verbose_name_plural": "Weekly Mining Poll Configs",
                "default_permissions": (),
            },
        ),
        migrations.CreateModel(
            name="WeeklyMiningPollRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("main", "Main"), ("tiebreaker", "Tiebreaker")],
                        default="main",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_post", "Pending post"),
                            ("open", "Open"),
                            ("pending_resolution", "Pending resolution"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending_post",
                        max_length=32,
                    ),
                ),
                ("tiebreak_round", models.PositiveSmallIntegerField(default=0)),
                ("duration_hours", models.PositiveSmallIntegerField(default=24)),
                ("discord_channel_id", models.BigIntegerField()),
                ("discord_message_id", models.BigIntegerField(blank=True, null=True)),
                ("ping_role_id", models.BigIntegerField(blank=True, null=True)),
                ("question_text", models.CharField(max_length=300)),
                ("option_labels", models.JSONField(blank=True, default=list)),
                ("display_option_labels", models.JSONField(blank=True, default=list)),
                ("previous_winner_option", models.CharField(blank=True, max_length=55)),
                ("winning_option", models.CharField(blank=True, max_length=55)),
                ("resolution_method", models.CharField(blank=True, max_length=32)),
                ("total_votes", models.PositiveIntegerField(blank=True, null=True)),
                ("resolution_attempts", models.PositiveSmallIntegerField(default=0)),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("closes_at", models.DateTimeField(blank=True, null=True)),
                ("resolve_after", models.DateTimeField(blank=True, null=True)),
                ("finalized_at", models.DateTimeField(blank=True, null=True)),
                ("failure_reason", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "config",
                    models.ForeignKey(
                        on_delete=models.deletion.CASCADE,
                        related_name="runs",
                        to="indy_hub.weeklyminingpollconfig",
                    ),
                ),
                (
                    "parent_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.deletion.CASCADE,
                        related_name="child_runs",
                        to="indy_hub.weeklyminingpollrun",
                    ),
                ),
                (
                    "root_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=models.deletion.CASCADE,
                        related_name="descendant_runs",
                        to="indy_hub.weeklyminingpollrun",
                    ),
                ),
            ],
            options={
                "verbose_name": "Weekly Mining Poll Run",
                "verbose_name_plural": "Weekly Mining Poll Runs",
                "default_permissions": (),
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="weeklyminingpollconfig",
            index=models.Index(
                fields=["is_active"], name="indy_hub_wmp_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weeklyminingpollconfig",
            index=models.Index(
                fields=["last_scheduled_post_at"], name="indy_hub_wmp_last_post_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="weeklyminingpollrun",
            index=models.Index(
                fields=["status", "resolve_after"],
                name="indy_hub_wmpr_resolve_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="weeklyminingpollrun",
            index=models.Index(
                fields=["config", "created_at"],
                name="indy_hub_wmpr_cfg_created_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="weeklyminingpollrun",
            index=models.Index(fields=["root_run"], name="indy_hub_wmpr_root_idx"),
        ),
    ]
