# Generated by ChatGPT on 2026-05-11

# Standard Library
import re

# Django
from django.db import migrations, models


DAY_NAME_TO_NUMBER = {
    "sun": "0",
    "mon": "1",
    "tue": "2",
    "wed": "3",
    "thu": "4",
    "fri": "5",
    "sat": "6",
}


def _normalize_day_of_week(raw_value: str) -> str:
    value = str(raw_value or "*").strip().lower()
    for name, number in DAY_NAME_TO_NUMBER.items():
        value = re.sub(rf"\b{name}\b", number, value)
    return value or "*"


def migrate_weekly_poll_crontabs(apps, schema_editor):
    WeeklyMiningPollConfig = apps.get_model("indy_hub", "WeeklyMiningPollConfig")
    CrontabSchedule = apps.get_model("django_celery_beat", "CrontabSchedule")

    for config in WeeklyMiningPollConfig.objects.all().iterator():
        day_of_week = _normalize_day_of_week(
            getattr(config, "cron_day_of_week", "*")
        )
        crontab, _ = CrontabSchedule.objects.get_or_create(
            minute=getattr(config, "cron_minute", "0") or "0",
            hour=getattr(config, "cron_hour", "0") or "0",
            day_of_week=day_of_week,
            day_of_month=getattr(config, "cron_day_of_month", "*") or "*",
            month_of_year=getattr(config, "cron_month_of_year", "*") or "*",
            timezone="UTC",
        )
        config.crontab_schedule_id = crontab.id
        config.save(update_fields=["crontab_schedule_id"])


class Migration(migrations.Migration):
    dependencies = [
        ("django_celery_beat", "0019_alter_periodictasks_options"),
        ("indy_hub", "0115_weekly_mining_polls"),
    ]

    operations = [
        migrations.AddField(
            model_name="weeklyminingpollconfig",
            name="crontab_schedule_id",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="ID of the django-celery-beat crontab schedule to reuse.",
                null=True,
            ),
        ),
        migrations.RunPython(
            migrate_weekly_poll_crontabs,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name="weeklyminingpollconfig",
            name="cron_day_of_month",
        ),
        migrations.RemoveField(
            model_name="weeklyminingpollconfig",
            name="cron_day_of_week",
        ),
        migrations.RemoveField(
            model_name="weeklyminingpollconfig",
            name="cron_hour",
        ),
        migrations.RemoveField(
            model_name="weeklyminingpollconfig",
            name="cron_minute",
        ),
        migrations.RemoveField(
            model_name="weeklyminingpollconfig",
            name="cron_month_of_year",
        ),
    ]
