# Generated by Django 4.2.20 on 2026-05-21 00:00

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indy_hub", "0100_materialexchangeconfig_container_price_overrides"),
    ]

    operations = [
        migrations.CreateModel(
            name="CompressedOreCache",
            fields=[
                ("ore_type_id", models.IntegerField(primary_key=True, serialize=False)),
                ("ore_name", models.CharField(max_length=255)),
                ("reprocessing_outputs", models.JSONField(default=dict)),
                (
                    "buy_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
                ),
                (
                    "sell_price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
                ),
                ("reprocessing_data_updated", models.DateTimeField(auto_now_add=True)),
                ("pricing_data_updated", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "default_permissions": (),
            },
        ),
        migrations.AddIndex(
            model_name="compressedorecache",
            index=models.Index(
                fields=["pricing_data_updated"],
                name="indy_hub_co_pricing_f8a2d7_idx",
            ),
        ),
    ]
