# Generated by Django 4.2.30 on 2026-05-21 19:13

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("indy_hub", "0116_weekly_mining_poll_crontab_reference"),
        ("indy_hub", "0117_compressedorecache"),
    ]

    operations = []
