# Generated by Django 4.2.20 on 2026-05-21 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indy_hub", "0101_compressedorecache"),
    ]

    operations = [
        migrations.AddField(
            model_name="compressedorecache",
            name="cache_version",
            field=models.IntegerField(default=1),
        ),
    ]
