# Generated by Django 4.2.20 on 2026-05-21 21:30

# Django
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("indy_hub", "0119_compressedorecache_cache_version"),
    ]

    operations = [
        migrations.AddField(
            model_name="materialexchangeconfig",
            name="buy_market_group_profiles",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text=(
                    "Saved buy-side market-group profiles. Each row can define "
                    "name, default flag, and selected market group IDs."
                ),
            ),
        ),
        migrations.AddField(
            model_name="materialexchangeconfig",
            name="sell_market_group_profiles",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text=(
                    "Saved sell-side market-group profiles. Each row can define "
                    "name, default flag, allow_all, and selected market group IDs."
                ),
            ),
        ),
    ]
