# Generated by Django 4.2.30 on 2026-05-21 19:30

# Django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("indy_hub", "0118_merge_20260521_1913"),
        ("indy_hub", "0119_compressedorecache_cache_version"),
    ]

    operations = []
