# Generated by Django 4.2.20 on 2026-05-21 21:40

# Django
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "indy_hub",
            "0116_weekly_mining_poll_crontab_reference",
        ),
        (
            "indy_hub",
            "0120_materialexchangeconfig_market_group_profiles",
        ),
    ]

    operations = []
