# Generated by Django 4.2.30 on 2026-05-21 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('indy_hub', '0120_merge_20260521_1930'),
        ('indy_hub', '0121_merge_0116_weekly_mining_poll_crontab_reference_0120_materialexchangeconfig_market_group_profiles'),
    ]

    operations = [
    ]
