# Generated by Django 4.2.30 on 2026-09-24 13:44

# Django
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("indy_hub", "0131_production_simulation_preferences"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="compressedorecache",
            new_name="indy_hub_co_pricing_2f3c2d_idx",
            old_name="indy_hub_co_pricing_f8a2d7_idx",
        ),
        migrations.RenameIndex(
            model_name="publicjitacontract",
            new_name="indy_hub_pu_is_acti_8f3141_idx",
            old_name="indy_hub_pu_is_acti_905bbf_idx",
        ),
        migrations.RenameIndex(
            model_name="publicjitacontract",
            new_name="indy_hub_pu_region__6852e9_idx",
            old_name="indy_hub_pu_region__a03667_idx",
        ),
        migrations.RenameIndex(
            model_name="publicjitacontract",
            new_name="indy_hub_pu_contrac_b0895d_idx",
            old_name="indy_hub_pu_contrac_d4fc28_idx",
        ),
        migrations.RenameIndex(
            model_name="publicjitacontract",
            new_name="indy_hub_pu_last_se_90ceea_idx",
            old_name="indy_hub_pu_last_se_680c73_idx",
        ),
        migrations.RenameIndex(
            model_name="publicjitacontract",
            new_name="indy_hub_pu_date_is_c2f7b7_idx",
            old_name="indy_hub_pu_date_is_a9841c_idx",
        ),
        migrations.RenameIndex(
            model_name="publicjitacontractitem",
            new_name="indy_hub_pu_contrac_0fe989_idx",
            old_name="indy_hub_pu_contrac_07c967_idx",
        ),
        migrations.RenameIndex(
            model_name="publicjitacontractitem",
            new_name="indy_hub_pu_type_id_509d16_idx",
            old_name="indy_hub_pu_type_id_0b2136_idx",
        ),
        migrations.RenameIndex(
            model_name="reprocessingserviceprofile",
            new_name="indy_hub_re_approva_0d42c1_idx",
            old_name="indy_hub_re_approva_b1f5f7_idx",
        ),
        migrations.RenameIndex(
            model_name="reprocessingserviceprofile",
            new_name="indy_hub_re_charact_f72a35_idx",
            old_name="indy_hub_re_charact_94e9a8_idx",
        ),
        migrations.RenameIndex(
            model_name="reprocessingserviceprofile",
            new_name="indy_hub_re_estimat_0a97de_idx",
            old_name="indy_hub_re_estima_7c7564_idx",
        ),
        migrations.RenameIndex(
            model_name="reprocessingservicerequest",
            new_name="indy_hub_re_status_ea983b_idx",
            old_name="indy_hub_re_status_681ee5_idx",
        ),
        migrations.RenameIndex(
            model_name="reprocessingservicerequest",
            new_name="indy_hub_re_request_1169e4_idx",
            old_name="indy_hub_re_request_f1b7d8_idx",
        ),
        migrations.RenameIndex(
            model_name="reprocessingservicerequest",
            new_name="indy_hub_re_process_8a0049_idx",
            old_name="indy_hub_re_process_357efd_idx",
        ),
        migrations.RenameIndex(
            model_name="reprocessingservicerequestitem",
            new_name="indy_hub_re_request_f114e9_idx",
            old_name="indy_hub_re_request_1822d6_idx",
        ),
        migrations.RenameIndex(
            model_name="reprocessingservicerequestoutput",
            new_name="indy_hub_re_request_f3b392_idx",
            old_name="indy_hub_re_request_aeb3ec_idx",
        ),
        migrations.RenameIndex(
            model_name="sdeindustryactivitymaterial",
            new_name="indy_hub_sd_eve_typ_0139d2_idx",
            old_name="indy_hub_sd_eve_typ_7a2e7e_idx",
        ),
        migrations.RenameIndex(
            model_name="sdeindustryactivitymaterial",
            new_name="indy_hub_sd_materia_b42c80_idx",
            old_name="indy_hub_sd_materi_4cf42a_idx",
        ),
        migrations.RenameIndex(
            model_name="sdeindustryactivityproduct",
            new_name="indy_hub_sd_eve_typ_7f8049_idx",
            old_name="indy_hub_sd_eve_typ_2d4c18_idx",
        ),
        migrations.RenameIndex(
            model_name="sdeindustryactivityproduct",
            new_name="indy_hub_sd_product_da15e2_idx",
            old_name="indy_hub_sd_produc_23b2bb_idx",
        ),
        migrations.RenameIndex(
            model_name="sdemarketgroup",
            new_name="indy_hub_sd_parent__5264ea_idx",
            old_name="indy_hub_sd_parent__ef0318_idx",
        ),
        migrations.AlterField(
            model_name="capitalshiporder",
            name="ship_class",
            field=models.CharField(
                choices=[
                    ("dread", "Dreadnought"),
                    ("carrier", "Carrier"),
                    ("fax", "Force Auxiliary"),
                    ("super", "Supercarrier"),
                    ("titan", "Titan"),
                    ("freighter", "Freighter"),
                    ("jump_freighter", "Jump Freighter"),
                    ("capital_indy", "Capital Industrial"),
                ],
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="sdeindustryactivitymaterial",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="sdeindustryactivityproduct",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
    ]
