# Generated by Django 4.2.27 on 2026-09-27 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indy_hub', '0132_rename_indy_hub_co_pricing_f8a2d7_idx_indy_hub_co_pricing_2f3c2d_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='capitalshiporder',
            name='upfront_payment_agreed_at',
            field=models.DateTimeField(blank=True, help_text='When the user acknowledged and agreed to the upfront payment terms.', null=True),
        ),
        migrations.AddField(
            model_name='capitalshiporder',
            name='upfront_payment_reason',
            field=models.TextField(blank=True, default='', help_text='The upfront payment reason at time of order creation.'),
        ),
        migrations.AddField(
            model_name='capitalshiporder',
            name='upfront_payment_refunds_allowed',
            field=models.BooleanField(default=False, help_text='Whether refunds are allowed if structure destroyed during build.'),
        ),
        migrations.AddField(
            model_name='capitalshiporder',
            name='upfront_payment_required',
            field=models.BooleanField(default=False, help_text='Whether upfront payment was required at time of order creation.'),
        ),
        migrations.AddField(
            model_name='materialexchangeconfig',
            name='capital_upfront_payment_reason',
            field=models.TextField(blank=True, default='', help_text='Custom reason / policy details displayed to pilots explaining why upfront payment is required.'),
        ),
        migrations.AddField(
            model_name='materialexchangeconfig',
            name='capital_upfront_payment_refunds_allowed',
            field=models.BooleanField(default=False, help_text='Indicates whether refunds are allowed if the production structure is destroyed during build.'),
        ),
        migrations.AddField(
            model_name='materialexchangeconfig',
            name='capital_upfront_payment_required',
            field=models.BooleanField(default=False, help_text='When enabled, capital orders require upfront payment before production begins.'),
        ),
    ]
