# Generated by Django 5.2.17 on 2026-10-05 02:01

import django.db.models.deletion
from django.db import migrations, models


def populate_simulation_products(apps, schema_editor):
    """Backfill ProductionSimulationProduct records for existing simulations."""
    ProductionSimulation = apps.get_model("indy_hub", "ProductionSimulation")
    ProductionSimulationProduct = apps.get_model(
        "indy_hub", "ProductionSimulationProduct"
    )

    products_to_create = []
    for sim in ProductionSimulation.objects.iterator():
        if sim.blueprint_type_id:
            products_to_create.append(
                ProductionSimulationProduct(
                    simulation=sim,
                    blueprint_type_id=sim.blueprint_type_id,
                    blueprint_name=sim.blueprint_name or f"Blueprint {sim.blueprint_type_id}",
                    runs=sim.runs or 1,
                    sort_order=0,
                )
            )

    if products_to_create:
        ProductionSimulationProduct.objects.bulk_create(products_to_create)


class Migration(migrations.Migration):

    dependencies = [
        ("indy_hub", "0133_capitalshiporder_upfront_payment_agreed_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productionsimulation",
            name="blueprint_name",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="productionsimulation",
            name="blueprint_type_id",
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="ProductionSimulationProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("blueprint_type_id", models.BigIntegerField()),
                ("blueprint_name", models.CharField(max_length=255)),
                ("runs", models.IntegerField(default=1)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "simulation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="indy_hub.productionsimulation",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
                "default_permissions": (),
                "indexes": [
                    models.Index(
                        fields=["simulation", "sort_order"],
                        name="indy_hub_pr_simulat_d4c838_idx",
                    ),
                    models.Index(
                        fields=["blueprint_type_id"],
                        name="indy_hub_pr_bluepri_48897f_idx",
                    ),
                ],
            },
        ),
        migrations.RunPython(populate_simulation_products, migrations.RunPython.noop),
    ]
